### ISSUE TITLE
List of software included in ISO via theLBX.io

### ISSUE THREAD

**Issue by BluePr1nt-X** [StratousLabs/LockBox#11]
1. Flathub
2. Snapcraft
3. Gufw Firewall
4. Gnome Feeds
5. Borg Backup/Vorta Backup
6. Brave Browser
7. LibraWolf
8. Chromium
9. KeypassXC
10. Eddy
11. Opensnitch
12. BTCRecover
13. GNOME Partition Editor

**Comment by l0cs** [comment]
This is better suited for the wiki
